Dat 2307 incomplete lineage for beers
datafold/dbt-beers pull request #39
Opened 2021-12-20 23:17 UTC by teraamp

Rewrote beers.sql from unions to generators and joins

2022-06-06 09:17 UTC, anatoly-scherbakov requested changes

2022-06-06 09:17 UTC, anatoly-scherbakov commented on models/beers/order_lines.sql
> +SELECT TO_VARCHAR(
I would suggest using `{{ date_format }}` [macro](https://github.com/datafold/dbt-beers/blob/master/macros/date_format.sql). We use this repo also for Databricks, which does not support `TO_VARCHAR`.

To test the repo against Databricks, you can use the command [provided in 1Password](https://share.1password.com/s#aWCXzjSBxi6iWS3KbIZqcfMPt1BC6EHNAWlwPu2yil4).

2022-07-11 06:37 UTC, teraamp commented on models/beers/order_lines.sql
> +SELECT TO_VARCHAR(
Updated.

2022-07-11 07:03 UTC, anatoly-scherbakov approved these changes

2022-07-12 08:38 UTC, merged